<?php
/**
 * @package	PaperRoll
 * @author 	dennis
 * @site 	www.drogers.net
 */
 ?>
<h2>Contact</h2>
<p>Email: <a href="mailto:spartacuswallpaper@gmail.com">spartacuswallpaper@gmail.com</a></p>
<p>Twitter: <a href="https://twitter.com/spartacuswalls">@spartacuswalls</a></p>
<p>Facebook: <a href="http://www.facebook.com/spartacuswallpaper">Spartacus Wallpaper</a></p>
<p>Tapiture: <a href="http://tapiture.com/spartacuswallpaper">Spartacus Wallpaper</a></p>
<p>Pinterest: <a href="http://www.pinterest.com/spartacuswalls/">spartacuswalls</a></p>