<?php
/**
 * @package		PaperRoll
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */
$date = new PaperRoll_View_Helper_Date();
?>

<?php foreach ($this->entries as $entry) : ?>

	<div class="entry">
		<h2 class="entry-title"><a href="/<?php echo $entry->getUrlPath()?>"><?php echo $entry->getTitle() ?></a></h2>
		<p class="entry-date"><?php echo $date->format($entry->getPublishedAt()) ?></p>
		<a href="/<?php echo $entry->getUrlPath()?>" class="entry-preview-image"><img src="<?php echo $entry->getImageUrl('preview') ?>" alt="<?php echo $entry->getTitle() ?>" /></a>
		<p class="entry-content"><?php echo $entry->getContent(); ?></p>
	</div>
<?php endforeach; ?>

<a href="<?php echo $this->url(array('controller'=>'entry','action'=>'index'), 'default') ?>">View All</a>