<?php
/**
 * @package		PaperRoll
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */

$columnCount = 3;
$i = 0;
$totalEntries = count($this->entries);
?>

<?php foreach ($this->entries as $entry): ?>
	<?php if($entry->canShow()): ?>
		<?php if ($i % $columnCount == 0) : ?>
			<ul class="entry-grid">
		<?php endif; ?>
				<li class="entry-item">
					<p class="entry-title"><a href="/<?php echo $entry->getUrlPath()?>" title="<?php echo $this->escape($entry->getTitle()) ?>"><?php echo $this->escape($entry->getTitle()) ?></a></p>
					<div class="entry-image"><a href="/<?php echo $entry->getUrlPath()?>"><img src="<?php echo $entry->getImageUrl('thumb') ?>" alt="<?php echo $entry->getTitle() ?>"/></a></div>
					<p class="entry-date"><?php echo Paper::helper("Date")->format($entry->getData('published_at'), true); ?></p>
				</li>
		<?php if (++$i % $columnCount == 0 || $i >= $totalEntries) : ?>
			</ul>
		<?php endif; ?>
	<?php endif; ?>
<?php endforeach ?>