<?php
/**
 * @package		PaperRoll
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */
?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $this->title ?>Desktop Backgrounds | Spartacus Wallpaper</title>
  <?php if($this->canonical): ?><link rel="canonical" href="<?php echo $this->canonical ?>" /><?php endif; ?>
  <?php echo $this->headLink()->appendStylesheet(Paper::getBaseUrl().'/public/css/global.css') ?>
</head>
<body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
	<div class="wrapper-outer">
		<div class="header-banner<?php echo Paper::helper('Date')->getBannerImage()?>">
			<div class="logo">
				<a href="<?php echo Paper::getBaseUrl() ?>"><img src="<?php echo Paper::getBaseUrl() ?>/public/images/logo.png" alt="Spartacus Wallpaper" /></a>
				<ul class="top-nav">
					<li><a href="<?php echo Paper::getBaseUrl() ?>/page/about">about</a></li>
					<li><a href="<?php echo Paper::getBaseUrl() ?>/page/tags">tags</a></li>
					<li><a href="<?php echo Paper::getBaseUrl() ?>/page/contact">contact</a></li>
					<li><a href="<?php echo Paper::getBaseUrl() ?>/page/donate">donate</a></li>
				</ul>
			</div>
		</div>
		<div class="wrapper-inner">
			<div class="sidebar">
				<div class="sidebar-head"></div>
				<p class="section-head">Wallpapers:</p>
				<ul>
				<?php $kinds = new PaperRoll_Model_ImageKind(); ?>
				<?php foreach ($kinds->getTagLinks() as $kind) : ?>
					<li><a href="<?php echo Paper::getBaseUrl() ?>/tag/<?php echo $kind->getData('path') ?>"><?php echo $kind->getData('label') ?></a></li>
				<?php endforeach; ?>
				</ul>
				<p class="section-head">Archive by Year:</p>
				<ul class="years">
				<?php $tag = new PaperRoll_Model_Tag(); ?>
				<?php foreach ($tag->getYears() as $year) : ?>
					<li><a href="<?php echo Paper::getBaseUrl() ?>/tag/<?php echo $year ?>"><?php echo $year ?></a></li>
				<?php endforeach; ?>
				</ul>
				<p class="section-head">Top 20:</p>
				<ul>
				<?php foreach ($tag->getTop(20) as $tag) : ?>
					<li><a href="<?php echo Paper::getBaseUrl() ?>/tag/<?php echo $tag->getData('slug') ?>"><?php echo $tag->getData('title') ?></a></li>
				<?php endforeach; ?>
				</ul>
				<div class="ad-sidebar">
					<script type="text/javascript"><!--
					google_ad_client = "pub-9622612302631221";
					/* 120x600, created 12/14/09 */
					google_ad_slot = "6772196842";
					google_ad_width = 140;
					google_ad_height = 600;
					//-->
					</script>
					<script type="text/javascript"
					src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</div>
			</div>
			<div class="content">
				<div class="content-head"></div>
				<div class="ad-top">
					<script type="text/javascript"><!--
					google_ad_client = "pub-9622612302631221";
					/* 728x15, created 12/30/09 */
					google_ad_slot = "7425641670";
					google_ad_width = 728;
					google_ad_height = 15;
					//-->
					</script>
					<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
				</div>
				<?php echo $this->layout()->content ?>
				<div class="ad-bottom">
					<script type="text/javascript"><!--
					google_ad_client = "pub-9622612302631221";
					/* 728x90, created 12/30/09 */
					google_ad_slot = "7751544997";
					google_ad_width = 728;
					google_ad_height = 90;
					//-->
					</script>
					<script type="text/javascript"
					src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</div>
			</div>
		</div>
	</div>
	<div id="copy">
		<p>Site design &copy;<?php echo date("Y") ?> by Spartacus Wallpaper.</p>
	</div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12138095-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	</body>
</html>