<?php
/**
 * @package		PaperRoll
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */
?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Spartacus Wallpaper</title>
  <?php echo $this->headLink()->appendStylesheet('/public/css/global.css') ?>
</head>
<body>
	<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
	<div id="admin">
		<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'index'), 'default', true) ?>" title="logout">admin</a>&nbsp;|&nbsp;
		<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'logout'), 'default', true) ?>" title="logout">logout</a>
	</div>
	<?php endif; ?>
	<div class="wrapper-outer">
		<div class="header-banner<?php echo Paper::helper('Date')->getBannerImage()?>">
			<div class="logo">
				<a href="/"><img src="/public/images/logo.png" alt="Spartacus Wallpaper" /></a>
				<ul class="top-nav">
					<li><a href="/page/about">about</a></li>
					<li><a href="/page/tags">tags</a></li>
					<li><a href="/page/contact">contact</a></li>
					<li><a href="/page/donate">donate</a></li>
				</ul>
			</div>
		</div>
		<div class="wrapper-inner">
			<div class="sidebar">
				<div class="sidebar-head"></div>
				<p class="section-head">Wallpapers:</p>
				<ul>
				<?php $kinds = new PaperRoll_Model_ImageKind(); ?>
				<?php foreach ($kinds->getTagLinks() as $kind) : ?>
					<li><a href="/tag/<?php echo $kind->getData('path') ?>"><?php echo $kind->getData('label') ?></a></li>
				<?php endforeach; ?>
				</ul>
				<p class="section-head">Archive by Year:</p>
				<ul class="years">
				<?php $tag = new PaperRoll_Model_Tag(); ?>
				<?php foreach ($tag->getYears() as $year) : ?>
					<li><a href="/tag/<?php echo $year ?>"><?php echo $year ?></a></li>
				<?php endforeach; ?>
				</ul>
				<p class="section-head">Top 20:</p>
				<ul>
				<?php foreach ($tag->getTop(20) as $tag) : ?>
					<li><a href="/tag/<?php echo $tag->getData('slug') ?>"><?php echo $tag->getData('title') ?></a></li>
				<?php endforeach; ?>
				</ul>
				<div class="ad-sidebar">
					<script type="text/javascript"><!--
					google_ad_client = "pub-9622612302631221";
					/* 120x600, created 12/14/09 */
					google_ad_slot = "6772196842";
					google_ad_width = 140;
					google_ad_height = 600;
					//-->
					</script>
					<script type="text/javascript"
					src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</div>
			</div>
			<div class="content">
				<div class="content-head"></div>
				<div class="ad-top">
					<script type="text/javascript"><!--
					google_ad_client = "pub-9622612302631221";
					/* 728x15, created 12/30/09 */
					google_ad_slot = "7425641670";
					google_ad_width = 728;
					google_ad_height = 15;
					//-->
					</script>
					<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
				</div>
				<?php echo $this->layout()->content ?>
				<div class="ad-bottom">
					<script type="text/javascript"><!--
					google_ad_client = "pub-9622612302631221";
					/* 728x90, created 12/30/09 */
					google_ad_slot = "7751544997";
					google_ad_width = 728;
					google_ad_height = 90;
					//-->
					</script>
					<script type="text/javascript"
					src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</div>
			</div>
		</div>
	</div>
	<div id="copy">
		<p>Site design &copy;<?php echo date("Y") ?> by <a href="http://drogers.net">Dennis Rogers</a>.</p>
	</div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12138095-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	</body>
</html>