<?php
/**
 * @package		PaperRoll
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */
?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Paper Roll Beta</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Paper Roll Beta</b>
    </div>
	<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
    <div style="float:right">
		<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'logout'), 'default') ?>" title="logout">logout</a>
    </div>
	<?php endif; ?>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>