<?php
/**
 * @package		PaperRoll
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */
?>

Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
	    <?php if($entry->canShow()): ?>
	    <dt><a href="/<?php echo $entry->getUrlPath()?>"><?php echo $this->escape($entry->getTitle()) ?></a></dt>
	    <dd><img src="<?php echo $entry->getThumb() ?>" alt="<?php echo $entry->getTitle() ?>"/></dd>
	    <?php endif; ?>
    <?php endforeach ?>
</dl>