<?php
/**
 * @package		PaperRoll
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */
$date = new PaperRoll_View_Helper_Date();
$entry = $this->entry
?>

<div class="entry-view">
	<h2 class="entry-title"><?php echo $entry->getTitle() ?></h2>
	<p class="entry-date"><?php echo $date->format($entry->getPublishedAt()) ?></p>
	<a href="<?php echo $entry->getFirstImage()->getUrl() ?>" class="entry-preview-image">
<img src="<?php echo $entry->getImageUrl('preview') ?>" alt="<?php echo $entry->getTitle() ?>" title="<?php echo $entry->getTitle() ?>"/></a>
	<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
		<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'edit','id'=>$entry->getData('id'))) ?>">Edit</a>
	<?php endif; ?>
    <?php /*
foreach ($entry->getImages() as $image) : ?>
        <?php if(preg_match("#iphone#", $image->getKind()->getPath())): ?>
        <a class="mobile-preview" href="<?php echo $image->getUrl() ?>" alt="<?php echo $image->getKind()->getLabel() ?>">
            <img src="<?php echo $image->getUrl() ?>" />
        </a>
        <?php endif; ?>
    <?php endforeach;
*/ ?>
	<p class="entry-content"><?php echo $entry->getContent() ?></p>
	<div class="social-media">
        <?php $shareUrl = "http://spartacuswallpaper.com/" . $entry->getUrlPath(); ?>
        <?php $title = urlencode($entry->getTitle()); ?>
        <ul>
            <li><a class="facebook" href="http://www.facebook.com/share.php?u=<?php echo $shareUrl ?>&title=<?php echo $title ?>">Share</a></li>
            <li><a class="tapiture" href="http://tapiture.com/widget/tap?url=<?php echo urlencode($entry->getImageUrl('preview')) ?>&page_url=<?php echo urlencode($shareUrl) ?>&page_title=<?php echo $title ?>&img_title=<?php echo $title ?>&img_width=724img_height=453">Tap</a></li>
            <li><a class="twitter" href="http://twitter.com/intent/tweet?url=<?php echo $shareUrl ?>&text=<?php echo $title ?>+-+<?php echo $entry->getImageUrl('preview') ?>&hashtags=wallpaper,background">Tweet</a></li>
            <li><a class="pinterest" href="http://pinterest.com/pin/create/bookmarklet/?media=<?php echo $entry->getImageUrl('preview') ?>&url=<?php echo $shareUrl ?>&is_video=false&description=<?php echo $title ?>">Pin</a></li>
        </ul>
	</div>
	<div class="entry-versions">
		<h4>Versions</h4>
		<ul>
		<?php foreach ($entry->getImages() as $image) : ?>
			<?php if ($image->getKind()->getPosition()) : ?>
				<li><a href="<?php echo $image->getUrl() ?>" alt="<?php echo $image->getKind()->getLabel() ?>"><?php echo $image->getKind()->getLabel() ?></a></li>
			<?php endif; ?>
		<?php endforeach; ?>
		</ul>
	</div>
	<div class="entry-tags">
		<h4>Tags</h4>
        <ul>
        <?php foreach ($entry->getTags() as $tag): ?>
            <li><a href="<?php echo $tag['url'] ?>"><?php echo $tag['title'] ?></a></li>
        <?php endforeach; ?>
        </ul>
	</div>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        var disqus_shortname = 'spartacuswallpaper';
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

</div>