<?php
/**
 * @package		PaperRoll
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */
$date = new PaperRoll_View_Helper_Date();
$entry = $this->entry
?>

<div class="entry-view">
	<h2 class="entry-title"><?php echo $entry->getTitle() ?></h2>
	<p class="entry-date"><?php echo $date->format($entry->getPublishedAt()) ?></p>
	<a href="<?php echo $entry->getFirstImage()->getUrl() ?>" class="entry-preview-image">
<img src="<?php echo $entry->getImageUrl('preview') ?>" alt="<?php echo $entry->getTitle() ?>" title="<?php echo $entry->getTitle() ?>"/></a>
	<p class="entry-content"><?php echo $entry->getContent() ?></p>
	<div class="social-media">
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		<div class="fb-like" data-href="<?php echo $entry->getUrlPath() ?>" data-send="false" data-width="250" data-show-faces="false" data-colorscheme="dark" data-font="arial"></div>
		<div class="twitter">
			<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://spartacuswallpaper.com/<?php echo $entry->getUrlPath() ?>" data-text="<?php echo $entry->getTitle() ?>" data-via="spartacuswalls">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		</div>
		<div class="pinterest">
			<a href="http://pinterest.com/pin/create/button/?url=<?php echo $entry->getUrlPath() ?>&media=<?php echo $entry->getImageUrl('preview') ?>&description=<?php echo $entry->getTitle() ?>" class="pin-it-button" count-layout="horizontal"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
			<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
		</div>
	</div>
	<div class="entry-versions">
		<h4>Versions</h4>
		<ul>
		<?php foreach ($entry->getImages() as $image) : ?>
			<?php if ($image->getKind()->getPosition()) : ?>
				<li><a href="<?php echo $image->getUrl() ?>" alt="<?php echo $image->getKind()->getLabel() ?>"><?php echo $image->getKind()->getLabel() ?></a></li>
			<?php endif; ?>
		<?php endforeach; ?>
		</ul>
	</div>
	<div class="entry-tags">
		<h4>Tags</h4>
		<?php
			$tags = array();
			foreach ($entry->getTags() as $tag){
				$tags[] = "<a href=\"{$tag['url']}\">{$tag['title']}</a>";
			}
			echo implode(", ", $tags);
		?>
	</div>
</div>