<?php
/**
 * @package	PaperRoll
 * @author 	dennis
 * @site 	www.drogers.net
 */
 ?>

<?php
$form = new Zend_Form(array(
	"action" => "/admin/save",
	"method" => "post"
));

	$form->addElement('text', 'title', array(
		'filters'    => array('StringTrim'),
		'required'   => true,
		'label'      => 'title:',
	));

	$content = $form->addElement('textarea', 'content', array(
		'label'		=> 'content:',
		'cols'		=> '40',
		'rows'		=> '5',
	));

	if($this->entry == null || $this->entry->getData('queue') != null){
	$queue = $form->addElement('select', 'queue', array(
		'label'		=> 'queue:',
		'multiOptions'	=> array(
			'1' => "Normal",
			'2' => "Calendar"
		)
	));
	}

	$form->addElement('textarea', 'tags', array(
		'filters'    => array('StringTrim'),
		'required'   => true,
		'label'      => 'tags:',
		'cols'		=> '40',
		'rows'		=> '5',
	));

	$form->addElement('text', 'url_path', array(
		'filters'    => array('StringTrim'),
		'required'   => true,
		'label'      => 'url path:',
	));

	$form->addElement('hidden', 'filename', array());

	$login = $form->addElement('submit', 'save', array(
		'required' => false,
		'ignore'   => true,
		'label'    => 'save',
	));

	$form->setDecorators(array(
		'FormElements',
		array('HtmlTag', array('tag' => 'dl', 'class' => 'zend_form')),
		array('Description', array('placement' => 'prepend')),
		'Form'
	));

if($this->entry){
	$form->addElement('hidden', 'id', array());
	$form->populate($this->entry->getData());
	$tags = array();
	foreach($this->entry->getTags() as $tag){
		$tags[] = $tag['slug'];
	}
	$form->populate(array("tags" => implode(",", $tags)));
	$image = $this->entry->getImageUrl('thumb');
} else if($this->image){
	$image = "/public/gallery/thumb/".$this->image;
	$tag = str_replace(".jpg", "", $this->image);
	$form->populate(array(
		'title'	=> Paper::helper('name')->fileToName($this->image),
		'tags'  => Paper::helper('name')->stripRoman($tag),
		'url_path' => $tag.".html",
		'filename' => $this->image
	));
}
?>
<?php if (isset($image)) : ?>
	<img style="float:right" src="<?php echo $image ?>" />
<?php endif; ?>
<?php echo $form; ?>
<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'index'), 'default', true) ?>" title="logout">&lt; back</a>
